// Provision the fixed, no-email demo identities on the LearnCard network (ADR-0020).
//
// Idempotent: derives the organization + recipient wallets from committed demo
// labels, ensures both network profiles exist, and mints the two bearer tokens
// the demo needs — a sender token (organization) for delivery, and a recipient
// read token for the Admin UI read-back. Writes them to a gitignored .env; re-run
// any time to regenerate. Run: `node provision.mjs` (needs network access to
// network.learncard.com).

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { initLearnCard } from '@learncard/init';

import { deriveSeed } from './derive.mjs';

// Load .env (anchored to this script's dir, not the CWD) BEFORE reading the
// demo-identity overrides below, so editing them in .env actually takes effect.
// Absent .env is fine on a first run — the committed defaults apply.
const envPath = join(dirname(fileURLToPath(import.meta.url)), '.env');
try {
  process.loadEnvFile(envPath);
} catch {
  // no .env yet — defaults below apply
}

const API_URL = process.env.LEARNCARD_API_URL || 'https://network.learncard.com/api';

// Demo identities are configuration, not secrets (see .env.example). Defaults
// keep the committed demo fixed; override in .env for a different demo run.
const RECIPIENT_LABEL = process.env.RECIPIENT_LABEL || 'learner';
const RECIPIENT_PROFILE_ID = process.env.RECIPIENT_PROFILE_ID || 'smi-demo-learner';
const ORGANIZATION_LABEL = process.env.ORGANIZATION_LABEL || 'organization';
const ORGANIZATION_PROFILE_ID = process.env.ORGANIZATION_PROFILE_ID || 'smi-demo-organization';

/** True when a createProfile rejection means the profile already exists (re-run). */
function isAlreadyExists(e) {
  return /exist|already|conflict|taken|duplicate/i.test((e?.message || e || '').toString());
}

async function ensureProfile(lc, profileId, displayName) {
  try {
    await lc.invoke.createProfile({ profileId, displayName });
    console.log(`  created profile ${profileId}`);
  } catch (e) {
    // Only an already-exists conflict is benign on re-run; any other failure
    // (bad displayName, network, auth/scope) must surface, not be mislabeled.
    if (!isAlreadyExists(e)) throw e;
    console.log(`  profile ${profileId} already exists`);
  }
  const me = await lc.invoke.getProfile();
  return me.did;
}

async function mintToken(lc, name, scope) {
  const grantId = await lc.invoke.addAuthGrant({ name, description: name, scope });
  return lc.invoke.getAPITokenForAuthGrant(grantId);
}

console.log('Provisioning demo identities on', API_URL);

const organization = await initLearnCard({ seed: deriveSeed(ORGANIZATION_LABEL), network: true });
const recipient = await initLearnCard({ seed: deriveSeed(RECIPIENT_LABEL), network: true });

console.log('Organization:');
const organizationDid = await ensureProfile(organization, ORGANIZATION_PROFILE_ID, 'SMI Demo Organization');
console.log('Recipient:');
const recipientDid = await ensureProfile(recipient, RECIPIENT_PROFILE_ID, 'SMI Demo Learner');

console.log('Minting tokens…');
// Scopes verified live: the send + received-list endpoints require the *plural*
// `credentials` resource (`credential:*` is rejected with a scope error).
const senderToken = await mintToken(organization, 'SMI demo sender', 'credentials:write');
const recipientToken = await mintToken(recipient, 'SMI demo read-back', 'credentials:read');

const env = [
  '# Generated by provision.mjs — gitignored, regenerable. Do not commit.',
  `LEARNCARD_API_URL=${API_URL}`,
  `LEARNCARD_API_TOKEN=${senderToken}`,
  `LEARNCARD_RECIPIENT_API_TOKEN=${recipientToken}`,
  `DEMO_RECIPIENT_PROFILE_ID=${RECIPIENT_PROFILE_ID}`,
  `DEMO_RECIPIENT_DID=${recipientDid}`,
  `DEMO_ORGANIZATION_PROFILE_ID=${ORGANIZATION_PROFILE_ID}`,
  `DEMO_ORGANIZATION_DID=${organizationDid}`,
  '',
].join('\n');
writeFileSync(envPath, env);

console.log('\n✅ Done. Wrote', envPath);
console.log(`   recipient:    ${RECIPIENT_PROFILE_ID}  (${recipientDid})`);
console.log(`   organization: ${ORGANIZATION_PROFILE_ID}  (${organizationDid})`);
console.log('   Seed the resolver mapping: learner -> profile_id above; copy tokens into service .env files.');
process.exit(0);
