// Provision the fixed, no-email demo identities on the LearnCard network (ADR-0020).
//
// Idempotent: derives the issuer + recipient wallets from committed demo labels,
// ensures both network profiles exist, and mints the two bearer tokens the demo
// needs — a sender token (issuer) for delivery, and a recipient read token for
// the Admin UI read-back. Writes them to a gitignored .env; re-run any time to
// regenerate. Run: `node provision.mjs` (needs network access to network.learncard.com).

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { initLearnCard } from '@learncard/init';

import {
  ISSUER_LABEL,
  ISSUER_PROFILE_ID,
  RECIPIENT_LABEL,
  RECIPIENT_PROFILE_ID,
  deriveSeed,
} from './derive.mjs';

const API_URL = process.env.LEARNCARD_API_URL || 'https://network.learncard.com/api';

async function ensureProfile(lc, profileId, displayName) {
  try {
    await lc.invoke.createProfile({ profileId, displayName });
    console.log(`  created profile ${profileId}`);
  } catch (e) {
    // Re-run: the profile already exists for this seed — that's fine.
    console.log(`  profile ${profileId} already exists (${(e?.message || e).toString().slice(0, 60)})`);
  }
  const me = await lc.invoke.getProfile();
  return me.did;
}

async function mintToken(lc, name, scope) {
  const grantId = await lc.invoke.addAuthGrant({ name, description: name, scope });
  return lc.invoke.getAPITokenForAuthGrant(grantId);
}

console.log('Provisioning demo identities on', API_URL);

const issuer = await initLearnCard({ seed: deriveSeed(ISSUER_LABEL), network: true });
const recipient = await initLearnCard({ seed: deriveSeed(RECIPIENT_LABEL), network: true });

console.log('Issuer:');
const issuerDid = await ensureProfile(issuer, ISSUER_PROFILE_ID, 'SMI Demo Issuer');
console.log('Recipient:');
const recipientDid = await ensureProfile(recipient, RECIPIENT_PROFILE_ID, 'SMI Demo Learner');

console.log('Minting tokens…');
// Scopes verified live: the send + received-list endpoints require the *plural*
// `credentials` resource (`credential:*` is rejected with a scope error).
const senderToken = await mintToken(issuer, 'SMI demo sender', 'credentials:write');
const recipientToken = await mintToken(recipient, 'SMI demo read-back', 'credentials:read');

const envPath = join(dirname(fileURLToPath(import.meta.url)), '.env');
const env = [
  '# Generated by provision.mjs — gitignored, regenerable. Do not commit.',
  `LEARNCARD_API_URL=${API_URL}`,
  `LEARNCARD_API_TOKEN=${senderToken}`,
  `LEARNCARD_RECIPIENT_API_TOKEN=${recipientToken}`,
  `DEMO_RECIPIENT_PROFILE_ID=${RECIPIENT_PROFILE_ID}`,
  `DEMO_RECIPIENT_DID=${recipientDid}`,
  `DEMO_ISSUER_PROFILE_ID=${ISSUER_PROFILE_ID}`,
  `DEMO_ISSUER_DID=${issuerDid}`,
  '',
].join('\n');
writeFileSync(envPath, env);

console.log('\n✅ Done. Wrote', envPath);
console.log(`   recipient: ${RECIPIENT_PROFILE_ID}  (${recipientDid})`);
console.log(`   issuer:    ${ISSUER_PROFILE_ID}  (${issuerDid})`);
console.log('   Seed the resolver mapping: learner -> profile_id above; copy tokens into service .env files.');
process.exit(0);
